include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
  errors:
    invalid_annotation_target: ignore
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
