name: zishu_flutter
description: "紫薯直播 Flutter 客户端：核心解析、平台适配与 Windows/Web UI 宿主分层。"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  get: ^4.7.2
  video_player: ^2.9.2
  web_socket_channel: ^3.0.1
  web: ^1.1.1
  media_kit: ^1.2.6
  media_kit_video: ^2.0.1
  media_kit_libs_windows_video: ^1.0.11
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/config/
