/// 分类名归一组(display 中文名 → 各平台上游原始名别名,小写精确匹配)。
///
/// **生成文件**:从 SFVideoLive web 真源
/// `services/streaming-server/src/browse/category-name-remap.ts` 的
/// CATEGORY_GROUPS 逐条生成 —— 修改请改真源后重新生成,勿手改本文件。
/// 匹配口径与 web remapCategoryName 一致:trim + lowercase 精确匹配,
/// 未命中返回原名。twitch/soop 等海外平台的分类树与房间分类经由本表中文化。
library;

/// display 中文名 → 原始名别名列表(小写)。
const Map<String, List<String>> kCategoryGroups = {
  '阿尔比恩': ['albion online'],
  '艾尔登法环': ['elden ring'],
  '暗黑破坏神Ⅳ': ['diablo iv'],
  '暗区突围：无限': ['arena breakout: infinite'],
  '奥丁：神叛': ['odin: valhalla rising'],
  '宝可梦': ['pokémon'],
  '宝可梦：冠军': ['pokemon champions'],
  '宝可梦：黑/白': ['pokémon black/white'],
  '宝可梦：黑2/白2': ['pokémon black/white version 2'],
  '宝可梦：火红/叶绿': ['pokémon firered/leafgreen'],
  '宝可梦：晶灿钻石/明亮珍珠': ['pokémon brilliant diamond/shining pearl'],
  '宝可梦：绿宝石': ['pokémon emerald version'],
  '宝可梦：朱/紫': ['pokémon scarlet and violet'],
  '宝可梦大集结': ['pokémon unite'],
  '宝可梦GO': ['pokémon go'],
  '宝可梦TCG Pocket': ['pokémon trading card game: pocket'],
  '堡垒之夜': ['fortnite'],
  '碧蓝幻想Relink': ['granblue fantasy: relink'],
  '波比的游戏时间': ['poppy playtime'],
  '博德之门3': ['baldur\'s gate 3'],
  '彩虹六号：围攻': ['rainbow six siege'],
  '传送门2': ['portal 2'],
  'DNF手游': ['dungeon & fighter mobile', '地下城与勇士：起源'],
  '帝国时代2': ['age of empires ii'],
  '第一后裔': ['the first descendant'],
  '钓鱼教学': ['how to fish'],
  // 注意:该别名本身含逗号(web 真源为单一别名 "animals, aquariums, and
  // zoos"),不能按逗号拆分。
  '动物与动物园': ['animals, aquariums, and zoos'],
  '二重螺旋': ['duet night abyss'],
  '方舟：生存进化': ['ark: survival ascended'],
  '复古游戏': ['retro', 'retro game'],
  '共同工作与自习': ['co-working & studying'],
  '怪物猎人': ['monster hunter world: iceborne'],
  '怪物猎人：荒野': ['monster hunter wilds'],
  '鬼武者 Way of the Sword': ['onimusha: way of the sword'],
  '国际象棋': ['chess'],
  '韩联社新闻': ['yonhapnews'],
  '黑色沙漠': ['black desert'],
  '黑神话：悟空': ['black myth: wukong'],
  '呼吸边缘2': ['breathedge 2'],
  '弧光猎人(ARC Raiders)': ['arc raiders'],
  '户外': ['irl'],
  '环世界': ['rimworld'],
  '幻兽帕鲁': ['palworld'],
  '荒野大镖客2': ['red dead redemption ii'],
  '荒野乱斗': ['brawl stars'],
  '绘画': ['art'],
  '火箭联盟': ['rocket league'],
  '加密货币': ['crypto'],
  '剑星': ['stellar blade'],
  '僵尸毁灭工程': ['project zomboid'],
  '街头霸王6': ['street fighter 6'],
  '绝地潜兵2': ['helldivers 2'],
  '绝地求生': ['pubg: battlegrounds'],
  '绝区零': ['zenless zone zero'],
  '恐鬼症': ['phasmophobia'],
  '老虎机': ['slots'],
  '黎明杀机': ['dead by daylight'],
  '聊天': ['just chatting'],
  '聊天/秀场': ['talk/cam'],
  // SOOP categoryList 实测直出英文原名的分类(其余项该接口已返中文)。
  '其他游戏': ['other games'],
  '猎杀：对决': ['hunt: showdown 1896'],
  '流放之路': ['path of exile'],
  '流放之路2': ['path of exile 2'],
  '龙珠Z：卡卡洛特': ['dragon ball z: kakarot'],
  '炉石传说': ['hearthstone'],
  '罗布乐思': ['roblox'],
  '洛奇手游': ['mabinogi mobile'],
  '马里奥赛车世界': ['mario kart world'],
  '马里奥制造': ['super mario maker 2'],
  '麦登橄榄球27': ['madden nfl 27'],
  '漫威争锋': ['marvel rivals'],
  '漫威终极逆转': ['marvel snap'],
  '冒险岛': ['maplestory'],
  '冒险岛：放置RPG': ['maplestory: idle rpg'],
  '冒险岛手游': ['maplestory m'],
  '冒险岛Worlds': ['maplestory worlds'],
  '美少女梦工厂：启示之子': ['princess maker: children of revelation'],
  '鸣潮': ['wuthering waves'],
  '命运2': ['destiny 2'],
  '命运方舟': ['失落方舟'],
  '模拟人生': ['the sims 4'],
  '魔兽世界': ['world of warcraft'],
  '魔兽争霸3': ['魔兽争霸iii'],
  '木卫四协议': ['the callisto protocol'],
  '女神异闻录3 Reload': ['persona 3 reload'],
  '女神异闻录5': ['persona 5 royal'],
  '欧洲卡车模拟2': ['euro truck simulator 2'],
  '匹诺曹的谎言': ['lies of p'],
  '扑克': ['poker'],
  '七日世界': ['once human'],
  '其他': ['other games'],
  '其他财经': ['other finance'],
  '全境封锁2': ['tom clancys the division 2'],
  '拳皇98': ['the king of fighters 98'],
  '雀魂': ['mahjong soul'],
  '人中之龙 维新!': ['like a dragon: ishin!'],
  '人中之龙8': ['like a dragon: infinite wealth'],
  '任天堂明星大乱斗：特别版': ['super smash bros. ultimate'],
  '瑞奇与叮当': ['ratchet & clank: rift apart'],
  '塞尔达传说：旷野之息': ['the legend of zelda breath of the wild'],
  '塞尔达传说：王国之泪': ['the legend of zelda tears of the kingdom'],
  '赛道狂飙': ['trackmania'],
  '三角洲行动': ['delta force'],
  '杀戮尖塔2': ['slay the spire 2'],
  '上古世纪': ['archeage'],
  '胜利女神：妮姬': ['goddess of victory：nikke'],
  '失控进化-RUST': ['rust'],
  '实况足球': ['efootball 2024'],
  '使命召唤': ['call of duty'],
  '使命召唤：黑色行动7': ['call of duty: black ops 7'],
  '使命召唤：战区': ['call of duty: warzone'],
  '守望先锋': ['overwatch'],
  '守望先锋2': ['overwatch 2'],
  '斯普拉遁3': ['splatoon 3'],
  '死锁': ['deadlock'],
  '死亡空间': ['dead space'],
  '索尼克 未知边境': ['sonic frontiers'],
  '泰拉瑞亚': ['terraria'],
  '坦克世界': ['world of tanks'],
  '坦克世界闪击战': ['tanks blitz'],
  '逃离塔科夫': ['escape from tarkov'],
  '逃生：试炼': ['the outlast trials'],
  '特别活动': ['special events'],
  '特种部队': ['special force'],
  '体育': ['sports'],
  '脱口秀与播客': ['talk shows & podcasts'],
  '万圣节': ['halloween: the game'],
  '万智牌': ['magic: the gathering'],
  '王权与自由': ['throne and liberty'],
  '王者荣耀': ['honor of kings'],
  '我的世界': ['minecraft'],
  '卧龙：苍天陨落': ['wo long: fallen dynasty'],
  '无尽对决': ['mobile legends: bang bang'],
  '无畏契约': ['valorant'],
  '消逝的光芒': ['dying light'],
  '小骨：英雄杀手': ['skul: the hero slayer'],
  '心灵杀手2': ['alan wake ii'],
  '星际公民': ['star citizen'],
  '星际战甲': ['warframe'],
  '星露谷物语': ['stardew valley'],
  '星球大战 绝地：幸存者': ['star wars jedi: survivor'],
  '虚拟赌场': ['virtual casino'],
  '音乐': ['music'],
  '英雄联盟': ['league of legends'],
  '英雄联盟手游': ['league of legends: wild rift'],
  '英雄无敌3': ['heroes of might and magic iii: the restoration of erathia'],
  '永恒轮回': ['eternal return'],
  '永恒之塔2': ['aion 2'],
  '永劫无间': ['naraka: bladepoint'],
  '游戏王：大师决斗': ['yu-gi-oh! master duel'],
  '游戏与试玩': ['games + demos'],
  '游泳': ['swimming'],
  '原神': ['genshin', 'genshin impact'],
  '云顶之弈': ['teamfight tactics', 'lol云顶之弈'],
  '战地6': ['battlefield 6'],
  '战舰世界': ['world of warships'],
  '战神：诸神黄昏': ['god of war ragnarök'],
  '致命公司': ['lethal company'],
  '致命躯壳2': ['mortal shell ii'],
  '智力运动': ['mind sports'],
  '棕色尘埃2': ['brown dust ii'],
  '足球经理': ['football manager 2024'],
  '足球经理26': ['football manager 2026', 'football manager 26'],
  '最后生还者 第二部': ['the last of us part ii remastered'],
  '最终幻想14': ['final fantasy xiv online'],
  'APEX英雄': ['apex legends'],
  'CS': ['counter-strike'],
  'CS2': ['counter-strike 2'],
  'DNF': ['地下城与勇士'],
  'DOTA2': ['dota 2', '刀塔2'],
  'FC Online足球在线': ['fc online'],
  'FC24': ['ea sports fc 24'],
  'FC26': ['ea sports fc 26'],
  'GTA5': ['grand theft auto v'],
  'MBN电视台': ['mbn'],
  'YTN 直播': ['ytn live'],
};

/// 原始名(小写) → display 中文名;模块加载时反转构建一次,查询 O(1)。
final Map<String, String> _rawToDisplay = {
  for (final entry in kCategoryGroups.entries)
    for (final alias in entry.value) alias: entry.key,
};

/// 海外平台原始分类名 → web 真源归一组展示名;未命中返回原名。
String remapCategoryName(String site, String name) {
  final key = name.trim().toLowerCase();
  return _rawToDisplay[key] ?? name;
}
